@port = 3567
@hostname = 127.0.0.1
@protocol = http
@base = {{hostname}}:{{port}}

GET https://{{base}}/
###
GET https://{{base}}/healthcheck
###
GET https://{{base}}/no_page_here
###
GET https://{{base}}/get_note?id=my note id
###
GET https://{{base}}/get_note?id=bad note id 😎
###

POST{{base}}/set_note
Content-Type: application/json

{
    "id": "my note id",
    "content": "yarr, here be content"
}

###

GET https://{{base}}/exists?search=notherelol