GET http://127.0.0.1:3000/healthcheck


###


GET http://127.0.0.1:3000/nothere


###

POST http://127.0.0.1:3000/set_note
Content-Type: application/json

{
    "id": "my note id",
    "content": "yarr, here be content"
}